"""Regenerate assets/data/site-data.js from the Eyescord source tree.

Run after a new release or after `pnpm generatePluginJson` in the Eyescord repo:

    python tools/build-data.py

It reads the client version, the installer version, plugins.json, and the built
installer, copies the installer into downloads/, and records its size and SHA-256
so the download page always matches the file actually being served.
"""

import hashlib
import json
import shutil
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else SITE.parent / "Eyescord"

INSTALLER_SRC = SRC / "release" / "installer" / "EYESCORD-Installer.exe"
INSTALLER_NAME = "Eyescord-Installer.exe"


def read_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def clean(text: str) -> str:
    # plugins.json was generated on Windows and some descriptions carry
    # UTF-8 bytes that were decoded as cp1252 on the way ("â€”" for "—").
    try:
        fixed = text.encode("cp1252").decode("utf-8")
        if fixed != text:
            text = fixed
    except (UnicodeEncodeError, UnicodeDecodeError):
        pass
    return " ".join(text.replace("EYESCORD", "Eyescord").split())


def main():
    client = read_json(SRC / "package.json")
    installer_pkg = read_json(SRC / "installer-src" / "package.json")

    plugins = []
    for p in read_json(SRC / "plugins.json"):
        exclusive = "eyescordplugins" in p["filePath"].lower()
        plugins.append({
            "name": clean(p["name"]),
            "description": clean(p.get("description", "")),
            "tags": p.get("tags") or [],
            "exclusive": exclusive,
            "required": bool(p.get("required")),
            "enabledByDefault": bool(p.get("enabledByDefault")),
            "commands": bool(p.get("hasCommands")),
        })
    plugins.sort(key=lambda p: p["name"].lower())

    installer = None
    if INSTALLER_SRC.exists():
        dest = SITE / "downloads" / INSTALLER_NAME
        dest.parent.mkdir(exist_ok=True)
        shutil.copy2(INSTALLER_SRC, dest)
        sha = hashlib.sha256(dest.read_bytes()).hexdigest()
        installer = {
            "file": f"downloads/{INSTALLER_NAME}",
            "bytes": dest.stat().st_size,
            "sha256": sha,
            "version": installer_pkg["version"],
        }
    else:
        print(f"warning: no installer at {INSTALLER_SRC}; download buttons will be disabled")

    data = {
        "version": client["version"],
        "installer": installer,
        "discord": "https://discord.gg/EYESCORD",
        "plugins": plugins,
    }

    out = SITE / "assets" / "data" / "site-data.js"
    # A .js file rather than .json so the site also works opened straight from disk,
    # where fetch() of a local file is blocked.
    out.write_text(
        "// Generated by tools/build-data.py. Do not edit by hand.\n"
        f"window.EYESCORD = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n",
        encoding="utf-8",
    )

    exclusive = sum(p["exclusive"] for p in plugins)
    print(f"v{data['version']}: {len(plugins)} plugins ({exclusive} exclusive) -> {out.relative_to(SITE)}")
    if installer:
        print(f"installer v{installer['version']}: {installer['bytes'] / 1e6:.1f} MB, sha256 {installer['sha256'][:16]}…")


if __name__ == "__main__":
    main()
